# Generated by Django 3.2 on 2021-04-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('gabinete', models.CharField(blank=True, db_column='Gabinete', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gcp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'GCP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProponenteExterno',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('profissao', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Proponente Externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProponenteInterno',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numeroualg', models.IntegerField(blank=True, db_column='numeroUALG', null=True)),
                ('curso', models.CharField(blank=True, max_length=255, null=True)),
                ('profissao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Proponente interno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicostecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ServicosTecnicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='Last_login', null=True)),
                ('is_superuser', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('contribuinte', models.IntegerField(blank=True, null=True)),
                ('datanascimento', models.DateTimeField(blank=True, db_column='dataNascimento', null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
