# Generated by Django 3.2 on 2021-04-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]
