# Generated by Django 3.2 on 2021-05-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'Campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('localizacao', models.CharField(blank=True, db_column='Localizaçao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=255, null=True)),
                ('cidade', models.CharField(db_column='Cidade', max_length=255)),
                ('endereco', models.CharField(db_column='Endereço', max_length=255)),
                ('codigopostal', models.CharField(db_column='CodigoPostal', max_length=255)),
                ('faturacao', models.CharField(blank=True, db_column='Faturacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255, unique=True)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'Equipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoRecurso',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Evento_Recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('fonte', models.CharField(db_column='Fonte', max_length=255)),
            ],
            options={
                'db_table': 'Recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('descricao', models.CharField(db_column='Descricao', max_length=255)),
            ],
            options={
                'db_table': 'Servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimedateRecurso',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TimeDate_Recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeequipamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipodeEquipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoespaco',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipoEspaco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposervico',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipoServico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadeorganica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'UnidadeOrganica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('localizacao', models.CharField(blank=True, db_column='Localizacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Universidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('tipo', models.CharField(db_column='Tipo', max_length=255)),
                ('capacidade', models.IntegerField(db_column='Capacidade')),
                ('mobilidade', models.BooleanField(db_column='Mobilidade')),
                ('edificioid', models.ForeignKey(blank=True, db_column='EdificioID', null=True,
                                                 on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='Recurso.edificio')),
            ],
            options={
                'db_table': 'Espaco',
                'managed': True,
            },
        ),
    ]
