# Generated by Django 3.2 on 2021-04-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('localizacao', models.CharField(blank=True, db_column='Localizaçao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('localizacao', models.CharField(blank=True, db_column='Localizaçao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('email', models.CharField(db_column='Email', max_length=255)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=255, null=True)),
                ('cidade', models.CharField(db_column='Cidade', max_length=255)),
                ('endereco', models.CharField(db_column='Endereço', max_length=255)),
                ('codigopostal', models.CharField(db_column='CodigoPostal', max_length=255)),
                ('faturacao', models.CharField(blank=True, db_column='Faturacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255, unique=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('reservado', models.IntegerField(blank=True, db_column='Reservado', null=True)),
                ('tipodeequipamentoid', models.IntegerField(db_column='TipodeEquipamentoID')),
            ],
            options={
                'db_table': 'Equipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade', models.IntegerField(db_column='Capacidade')),
                ('mobilidade', models.IntegerField(db_column='Mobilidade')),
                ('tipoespacoid', models.IntegerField(db_column='TipoEspacoid')),
            ],
            options={
                'db_table': 'Espaco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Evento_Recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('fonte', models.CharField(db_column='Fonte', max_length=255)),
                ('estado', models.IntegerField(db_column='Estado')),
            ],
            options={
                'db_table': 'Recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.IntegerField(db_column='Nome')),
            ],
            options={
                'db_table': 'Sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('reservada', models.TextField(db_column='Reservada')),
                ('tiposervicoid', models.IntegerField(db_column='TipoServicoid')),
            ],
            options={
                'db_table': 'Servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodeequipamento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.IntegerField(unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipodeEquipamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoespaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipoEspaco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposervico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(unique=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TipoServico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadeorganica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'UnidadeOrganica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('localizacao', models.CharField(blank=True, db_column='Localizacao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Universidade',
                'managed': False,
            },
        ),
    ]
