# Generated by Django 3.2 on 2021-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedateRecurso',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TimeDate_Recurso',
                'managed': False,
            },
        ),
    ]
