# Generated by Django 3.2 on 2021-04-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Neglected', '0001_initial'),
        ('Recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedateRecurso',
            fields=[
                ('timedateid', models.OneToOneField(db_column='TimeDateID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Neglected.timedate')),
            ],
            options={
                'db_table': 'TimeDate_Recurso',
                'managed': False,
            },
        ),
    ]
