# Generated by Django 3.2 on 2021-04-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacaonotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('pendente', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('lido', models.IntegerField()),
                ('emissorid', models.IntegerField(blank=True, null=True)),
                ('recetorid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'informacaonotificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('unread', models.IntegerField()),
                ('actor_object_id', models.CharField(max_length=255)),
                ('verb', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_object_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('public', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('emailed', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('action_object_content_type_id', models.IntegerField(blank=True, null=True)),
                ('actor_content_type_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
                ('target_content_type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacao',
                'managed': False,
            },
        ),
    ]
