# Generated by Django 3.2 on 2021-05-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('descricaogeral', models.CharField(db_column='DescricaoGeral', max_length=255)),
                ('maxparticipantes', models.IntegerField(db_column='MaxParticipantes')),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('visibilidade', models.CharField(blank=True, db_column='Visibilidade', default='Público', max_length=255, null=True)),
                ('inscritos', models.IntegerField(db_column='Num_participantes')),
                ('val_inscritos', models.IntegerField(db_column='Validacao_inscritos')),
            ],
            options={
                'db_table': 'Evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'Logistica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Templatecertificado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('destinatario', models.CharField(db_column='Destinatario', max_length=255)),
                ('dataemissao', models.CharField(db_column='DataEmissao', max_length=255)),
                ('formularioid', models.IntegerField(db_column='FormularioId')),
                ('eventoid', models.IntegerField(db_column='EventoID')),
            ],
            options={
                'db_table': 'TemplateCertificado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoevento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TipoEvento',
                'managed': False,
            },
        ),
    ]
