# Generated by Django 3.2 on 2021-04-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('descricaogeral', models.CharField(db_column='DescricaoGeral', max_length=255)),
                ('maxparticipantes', models.IntegerField(db_column='MaxParticipantes')),
                ('estado', models.CharField(blank=True, db_column='Estado', max_length=255, null=True)),
                ('visibilidade', models.CharField(blank=True, db_column='Visibilidade', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.IntegerField(blank=True, db_column='Nome', null=True)),
            ],
            options={
                'db_table': 'Logistica',
                'managed': False,
            },
        ),
    ]
