# Generated by Django 3.2 on 2021-04-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templatecertificado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('destinatario', models.CharField(db_column='Destinatario', max_length=255)),
                ('dataemissao', models.CharField(db_column='DataEmissao', max_length=255)),
                ('formularioid', models.IntegerField(db_column='FormularioId')),
                ('eventoid', models.IntegerField(db_column='EventoID')),
            ],
            options={
                'db_table': 'TemplateCertificado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoevento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TipoEvento',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
