# Generated by Django 3.2 on 2021-05-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilizadores', '0001_initial'),
        ('Inscricao', '0001_initial'),
        ('Evento', '0001_initial'),
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('conteudo', models.CharField(db_column='Conteudo', max_length=255)),
                ('obrigatorio', models.BooleanField(db_column='Obrigatorio')),
            ],
            options={
                'db_table': 'Campo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Respostaspossiveis',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'RespostasPossiveis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipocampo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoCampo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipoformulario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
                ('categoria', models.CharField(choices=[('0', 'Evento'), ('1', 'Inscrição'), ('2', 'Feedback')], db_column='Categoria', default='0', max_length=255)),
            ],
            options={
                'db_table': 'TipoFormulario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('teste', models.CharField(db_column='twste', max_length=255)),
                ('conteudo', models.CharField(db_column='Conteudo', max_length=255)),
                ('campoid', models.ForeignKey(blank=True, db_column='CampoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestorTemplates.campo')),
                ('eventoid', models.ForeignKey(blank=True, db_column='EventoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Evento.evento')),
                ('feedbackid', models.ForeignKey(blank=True, db_column='FeedbackId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Feedback.feedback')),
                ('inscricaoid', models.ForeignKey(blank=True, db_column='InscricaoId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Inscricao.inscricao')),
            ],
            options={
                'db_table': 'Resposta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', default='Sem título', max_length=255)),
                ('visibilidade', models.CharField(choices=[('0', 'Público'), ('1', 'Privado')], db_column='Visibilidade', default='0', max_length=255)),
                ('is_template', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], db_column='IsTemplate', default=0, verbose_name='É Template?')),
                ('eventoid', models.ForeignKey(db_column='eventoID', on_delete=django.db.models.deletion.DO_NOTHING, to='Evento.evento')),
                ('gcpid', models.ForeignKey(db_column='GCPid', on_delete=django.db.models.deletion.DO_NOTHING, to='Utilizadores.gcp')),
                ('tipoeventoid', models.ForeignKey(db_column='TipoEventoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Evento.tipoevento')),
                ('tipoformularioid', models.ForeignKey(db_column='TipoFormularioID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestorTemplates.tipoformulario')),
            ],
            options={
                'db_table': 'Formulario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campoid', models.ForeignKey(db_column='CampoID', on_delete=django.db.models.deletion.DO_NOTHING, to='GestorTemplates.campo')),
                ('formularioid', models.ForeignKey(db_column='FormularioId', on_delete=django.db.models.deletion.CASCADE, to='GestorTemplates.formulario')),
            ],
            options={
                'db_table': 'Campo_Formulario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='campo',
            name='respostapossivelid',
            field=models.ForeignKey(blank=True, db_column='RespostaPossivelId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GestorTemplates.respostaspossiveis'),
        ),
        migrations.AddField(
            model_name='campo',
            name='tipocampoid',
            field=models.ForeignKey(db_column='TipoCampoID', on_delete=django.db.models.deletion.DO_NOTHING, to='GestorTemplates.tipocampo'),
        ),
        migrations.CreateModel(
            name='GcpFormulario',
            fields=[
                ('gcpid', models.OneToOneField(db_column='GCPid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilizadores.gcp')),
                ('formularioid', models.ForeignKey(db_column='FormularioId', on_delete=django.db.models.deletion.DO_NOTHING, to='GestorTemplates.formulario')),
            ],
            options={
                'db_table': 'GCP_Formulario',
                'managed': True,
                'unique_together': {('gcpid', 'formularioid')},
            },
        ),
    ]
