# Generated by Django 3.2 on 2021-04-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('conteudo', models.CharField(db_column='Conteudo', max_length=255)),
                ('obrigatorio', models.TextField(db_column='Obrigatorio')),
                ('templateformularioid', models.IntegerField(blank=True, db_column='TemplateFormularioID', null=True)),
                ('formularioid', models.IntegerField(blank=True, db_column='FormularioId', null=True)),
            ],
            options={
                'db_table': 'Campo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Campo_Formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('visibilidade', models.CharField(db_column='Visibilidade', max_length=255)),
                ('templateformularioid', models.IntegerField(db_column='TemplateFormularioID')),
            ],
            options={
                'db_table': 'Formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GcpFormulario',
            fields=[
                ('gcpid', models.OneToOneField(db_column='GCPid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Utilizadores.gcp')),
            ],
            options={
                'db_table': 'GCP_Formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respostaspossiveis',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'RespostasPossiveis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Templatecertificado',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('destinatario', models.CharField(db_column='Destinatario', max_length=255)),
                ('dataemissao', models.CharField(db_column='DataEmissao', max_length=255)),
                ('formularioid', models.IntegerField(db_column='FormularioId')),
                ('eventoid', models.IntegerField(db_column='EventoID')),
            ],
            options={
                'db_table': 'TemplateCertificado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocampo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoCampo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoevento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
            ],
            options={
                'db_table': 'TipoEvento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoformulario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=255)),
            ],
            options={
                'db_table': 'TipoFormulario',
                'managed': False,
            },
        ),
    ]
