# Generated by Django 3.2 on 2021-04-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorTemplates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('conteudo', models.CharField(db_column='Conteudo', max_length=255)),
            ],
            options={
                'db_table': 'Resposta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Templatecertificado',
        ),
        migrations.DeleteModel(
            name='Tipoevento',
        ),
    ]
