# Generated by Django 3.2 on 2021-05-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestorTemplates', '0002_auto_20210511_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocampo',
            name='template',
            field=models.TextField(db_column='Template', default=''),
        ),
        migrations.AlterField(
            model_name='campo',
            name='campo_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestorTemplates.campo'),
        ),
    ]
