# Generated by Django 3.2 on 2021-05-19 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GestorTemplates', '0005_campo_position_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='created',
            field=models.DateTimeField(db_column='DataCriado', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formulario',
            name='updated',
            field=models.DateTimeField(blank=True, db_column='DataAtualizado', null=True),
        ),
    ]
