# Generated by Django 3.2 on 2021-05-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorTemplates', '0006_auto_20210519_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='visibilidade',
            field=models.CharField(choices=[('0', 'Público'), ('1', 'Privado')], db_column='Visibilidade', default='Não publicado', max_length=255),
        ),
    ]
