# Generated by Django 3.2 on 2021-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestorTemplates', '0007_alter_formulario_visibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='eventoid',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='visibilidade',
            field=models.CharField(choices=[('0', 'Privado'), ('1', 'Utilizadores da aplicação'), ('2', 'Público')], db_column='Visibilidade', default='0', max_length=255),
        ),
    ]
